# Generated by Django 4.2 on 2023-05-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_working_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True),
        ),
    ]
